### ISSUE TITLE
[FEATURE] Format actions should be dot-repeatable

### ISSUE THREAD

**Issue by neo451** [YousefHadder/markdown-plus.nvim#131]
## Feature Description
as titled, if I did `<leader>mc` on a word, and I should be able to `.` on another word and get a codespan.

## Use Case
repeating actions

## Proposed Solution
should be useful
https://gist.github.com/kylechui/a5c1258cd2d86755f97b10fc921315c3
https://www.vikasraj.dev/blog/vim-dot-repeat

## Alternatives Considered
actions can be real neovim "motions", that are paired with actual text objects, like you do `mciW`, I don't really know how to actually register a motion, do you emulate it or is there a good api around it, you can check out `mini.surround` for some ideas.

## Additional Context
none

**Comment by YousefHadder** [comment]
Done, thank you for raising this request.

**Comment by neo451** [comment]
@YousefHadder Thanks for the quick response, but after updating I got this error:

```
E5108: Lua: ...opt/markdown-plus.nvim/lua/markdown-plus/format/init.lua:61: 'buf' cannot be passed for global option 'operatorfunc'
stack traceback:
	[C]: in function '__newindex'
	...opt/markdown-plus.nvim/lua/markdown-plus/format/init.lua:61: in function <...opt/markdown-plus.nvim/lua/markdown-plus/format/init.lua:56>
```

I am running neovim nightly so that could be the reason, but not the most likely reason, see if you missed anything in the implementation

**Comment by YousefHadder** [comment]
Thank you pointing that out.
I don't know why it didn't fail on my end, turns out `operatorfunc` is a global-only option in Neovim, but the code was trying to set it as a buffer-local option using `vim.bo`.

Should be fixed, please let me know if it's working for you now.

**Comment by neo451** [comment]
works as intended now 👍
